version: "3.6"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - .pg_data:/var/lib/postgresql/data

  prometheus:
    image: bitnami/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
