version: "3.6"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - .pg_data:/var/lib/postgresql/data

  prometheus:
    image: bitnami/prometheus
    ports:
      - "9090:9090"
    command:
      - "--config.file=/app/prometheus.yml"
      - "--storage.tsdb.path=/opt/bitnami/prometheus/data"
      - "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries"
      - "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
    volumes:
      - .:/app

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
