version: "3.6"

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - .pg_data:/var/lib/postgresql/data
